when:
  - event: push
    branch: main
    path:
      include:
        - .woodpecker/deploy.yaml
        - packages/zones/data/**/*.yaml
        - "**/package.json"
        - "**/*.ts"
steps:
  - name: build
    image: oven/bun:1.3.11-alpine
    # language="sh"
    commands:
      - bun install
      - bun run --workspaces build
  - name: deploy
    image: stackexchange/dnscontrol:4.30.0
    environment:
      CREDS_JSON:
        from_secret: DNSCONTROL_CREDS_JSON
    # language="sh"
    commands:
      - cd config/dist/
      - printf '%s' "$${CREDS_JSON}" > creds.json
      - dnscontrol push
