when:
  - event: push
    branch: main
    path:
      include:
        - .woodpecker/docs.yaml
        - docs/**
steps:
  - name: build
    image: joshooaj/zensical:v0.0.24
    commands:
      - cd docs
      - zensical build
  - name: deploy
    image: jfxs/wrangler:4.73
    environment:
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: CLOUDFLARE_PAGES_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_PAGES_API_TOKEN
    commands:
      - wrangler pages deploy docs/build --project-name "$${CI_REPO_NAME}"
